name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_gcp_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}  # Pass GCP credentials
          TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}        # Pass GCP project ID
          TF_VAR_region: ${{ secrets.REGION }}                        # Pass region

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_gcp_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}  # Pass GCP credentials
          TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}        # Pass GCP project ID
          TF_VAR_region: ${{ secrets.REGION }}                        
